/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef decode_engine_CONSTANTS_H
#define decode_engine_CONSTANTS_H

#include "decode_engine_types.h"

namespace dengine {

class decode_engineConstants {
 public:
  decode_engineConstants();

};

extern const decode_engineConstants g_decode_engine_constants;

} // namespace

#endif
