/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "decode_engine_constants.h"

namespace dengine {

const decode_engineConstants g_decode_engine_constants;

decode_engineConstants::decode_engineConstants() {
}

} // namespace

