/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DecodeEngine_H
#define DecodeEngine_H

#include <thrift/TDispatchProcessor.h>
#include "decode_engine_types.h"

namespace dengine {

class DecodeEngineIf {
 public:
  virtual ~DecodeEngineIf() {}
  virtual void ping() = 0;
  virtual int32_t add(const int32_t num1, const int32_t num2) = 0;
};

class DecodeEngineIfFactory {
 public:
  typedef DecodeEngineIf Handler;

  virtual ~DecodeEngineIfFactory() {}

  virtual DecodeEngineIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(DecodeEngineIf* /* handler */) = 0;
};

class DecodeEngineIfSingletonFactory : virtual public DecodeEngineIfFactory {
 public:
  DecodeEngineIfSingletonFactory(const boost::shared_ptr<DecodeEngineIf>& iface) : iface_(iface) {}
  virtual ~DecodeEngineIfSingletonFactory() {}

  virtual DecodeEngineIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(DecodeEngineIf* /* handler */) {}

 protected:
  boost::shared_ptr<DecodeEngineIf> iface_;
};

class DecodeEngineNull : virtual public DecodeEngineIf {
 public:
  virtual ~DecodeEngineNull() {}
  void ping() {
    return;
  }
  int32_t add(const int32_t /* num1 */, const int32_t /* num2 */) {
    int32_t _return = 0;
    return _return;
  }
};


class DecodeEngine_ping_args {
 public:

  DecodeEngine_ping_args() {
  }

  virtual ~DecodeEngine_ping_args() throw() {}


  bool operator == (const DecodeEngine_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const DecodeEngine_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DecodeEngine_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DecodeEngine_ping_pargs {
 public:


  virtual ~DecodeEngine_ping_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DecodeEngine_ping_result {
 public:

  DecodeEngine_ping_result() {
  }

  virtual ~DecodeEngine_ping_result() throw() {}


  bool operator == (const DecodeEngine_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const DecodeEngine_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DecodeEngine_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DecodeEngine_ping_presult {
 public:


  virtual ~DecodeEngine_ping_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _DecodeEngine_add_args__isset {
  _DecodeEngine_add_args__isset() : num1(false), num2(false) {}
  bool num1;
  bool num2;
} _DecodeEngine_add_args__isset;

class DecodeEngine_add_args {
 public:

  DecodeEngine_add_args() : num1(0), num2(0) {
  }

  virtual ~DecodeEngine_add_args() throw() {}

  int32_t num1;
  int32_t num2;

  _DecodeEngine_add_args__isset __isset;

  void __set_num1(const int32_t val) {
    num1 = val;
  }

  void __set_num2(const int32_t val) {
    num2 = val;
  }

  bool operator == (const DecodeEngine_add_args & rhs) const
  {
    if (!(num1 == rhs.num1))
      return false;
    if (!(num2 == rhs.num2))
      return false;
    return true;
  }
  bool operator != (const DecodeEngine_add_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DecodeEngine_add_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DecodeEngine_add_pargs {
 public:


  virtual ~DecodeEngine_add_pargs() throw() {}

  const int32_t* num1;
  const int32_t* num2;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DecodeEngine_add_result__isset {
  _DecodeEngine_add_result__isset() : success(false) {}
  bool success;
} _DecodeEngine_add_result__isset;

class DecodeEngine_add_result {
 public:

  DecodeEngine_add_result() : success(0) {
  }

  virtual ~DecodeEngine_add_result() throw() {}

  int32_t success;

  _DecodeEngine_add_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const DecodeEngine_add_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const DecodeEngine_add_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DecodeEngine_add_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DecodeEngine_add_presult__isset {
  _DecodeEngine_add_presult__isset() : success(false) {}
  bool success;
} _DecodeEngine_add_presult__isset;

class DecodeEngine_add_presult {
 public:


  virtual ~DecodeEngine_add_presult() throw() {}

  int32_t* success;

  _DecodeEngine_add_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class DecodeEngineClient : virtual public DecodeEngineIf {
 public:
  DecodeEngineClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  DecodeEngineClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  int32_t add(const int32_t num1, const int32_t num2);
  void send_add(const int32_t num1, const int32_t num2);
  int32_t recv_add();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class DecodeEngineProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<DecodeEngineIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (DecodeEngineProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_add(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  DecodeEngineProcessor(boost::shared_ptr<DecodeEngineIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &DecodeEngineProcessor::process_ping;
    processMap_["add"] = &DecodeEngineProcessor::process_add;
  }

  virtual ~DecodeEngineProcessor() {}
};

class DecodeEngineProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  DecodeEngineProcessorFactory(const ::boost::shared_ptr< DecodeEngineIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< DecodeEngineIfFactory > handlerFactory_;
};

class DecodeEngineMultiface : virtual public DecodeEngineIf {
 public:
  DecodeEngineMultiface(std::vector<boost::shared_ptr<DecodeEngineIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~DecodeEngineMultiface() {}
 protected:
  std::vector<boost::shared_ptr<DecodeEngineIf> > ifaces_;
  DecodeEngineMultiface() {}
  void add(boost::shared_ptr<DecodeEngineIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  int32_t add(const int32_t num1, const int32_t num2) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add(num1, num2);
    }
    return ifaces_[i]->add(num1, num2);
  }

};

} // namespace

#endif
